const FETCH_ANNUAL_WARMING_DATA_ERROR = 'FETCH_ANNUAL_WARMING_DATA_ERROR';
const FETCH_ANNUAL_WARMING_DATA_PENDING = 'FETCH_ANNUAL_WARMING_DATA_PENDING';
const FETCH_ANNUAL_WARMING_DATA_SUCCESS = 'FETCH_ANNUAL_WARMING_DATA_SUCCESS';
const SET_COUNTRY_TO_VIEW = 'SET_COUNTRY_TO_VIEW';
const SET_TEMPERATURE_RANGE = 'SET_TEMPERATURE_RANGE';

export {
    FETCH_ANNUAL_WARMING_DATA_ERROR,
    FETCH_ANNUAL_WARMING_DATA_PENDING,
    FETCH_ANNUAL_WARMING_DATA_SUCCESS,
    SET_COUNTRY_TO_VIEW,
    SET_TEMPERATURE_RANGE
};
